<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A problem ocurred uploading your picture. Contact administrator' => 'Pri nalaganju vaše slike je prišlo do težave. Obrnite se na skrbnika',
    'An error ocurred deleting your file' => 'Pri brisanju datoteke je prišlo do napake',
    'Change' => 'Spremeni',
    'Remove' => 'Odstrani',
    'Remove avatar permanently? This can not be undone.' => 'Trajno odstraniti avatar? Tega ni mogoče razveljaviti.',
];
